pichik_development/pichik_development/urls.py
from django.contrib import admin
from django.urls import path, include
from webapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('webapp/', include('webapp.urls')) 
]

pichik_development/webapp/urls.py
from django.urls import path
from webapp import views

app_name = 'web_application'

urlpatterns = [
    path('firstlisting/',views.firstlisting,name="firstlisting"),
    path('secondlisting/',views.secondlisting,name="secondlisting"),
    path('thirdlisting/',views.thirdlisting,name="thirdlisting")
]

pichik_development/webapp/models.py
from django.db import models

# Create your models here.

pichik_development/webapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'webapp/index.html')

def firstlisting(request):
    return render(request, 'webapp/firstlisting.html')

def secondlisting(request):
    return render(request, 'webapp/secondlisting.html')

def thirdlisting(request):
    return render(request, 'webapp/thirdlisting.html')

pichik_development/webapp/templates/webapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Pichik Development</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
  </head>
  <body>
    <nav id="two" class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand" href="#">Pichik Development, LLC</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a id="col-one" class="nav-link" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a id="col-one" class="nav-link" href="#">Floor Plans</a>
          </li>
          <li class="nav-item dropdown">
            <a id="col-one" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Properties
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'web_application:firstlisting' %}">921 S 31st St</a>
              <a class="dropdown-item" href="{% url 'web_application:secondlisting' %}">827 S 30th Ct</a>
              <a class="dropdown-item" href="{% url 'web_application:thirdlisting' %}">825 S 30th Ct</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    {% block body_block %}
    {% endblock %}
  </body>
</html>

pichik_development/webapp/templates/webapp/firstlisting.html
<!DOCTYPE html>
{% extends "webapp/base.html" %}
{% load staticfiles %}

  {% block body_block %}
    <div class="container">
      <div id="jumbo1" class="jumbotron">
        <div class="media">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img id="car-img" src="{% static "images/thisone.jpg" %}"  alt="...">
              </div>
              <div class="carousel-item">
                <img id="car-img" src="{% static "images/thisone2.jpg" %}" alt="...">
              </div>
              <div class="carousel-item">
                <img id="car-img" src="{% static "images/thisone3.jpg" %}"  alt="...">
              </div>
              <div class="carousel-item">
                <img id="car-img" src="{% static "images/thisone4.jpG" %}"  alt="...">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <div class="media-body">
            <h5 class="mt-0">921 S 31st St Omaha, Nebraska</h5>
            Bedrooms: 2 <br>
            Bathrooms: 2.5 <br>
            Heating: Forced air <br>
            Floor size: 1,470 sqft <br>
            Rooms: 7 <br>
            Appliances: Dishwasher, Garbage Disposal, Microwave <br>
          </div>
        </div>
      </div>
    </div>

  {% endblock %}

pichik_development/webapp/templates/webapp/index.html
<!DOCTYPE html>
{% extends "webapp/base.html" %}
{% load staticfiles %}

  {% block body_block %}
      <div class="container">
        <div class="jumbotron" id="jumbo1">
            <h1>Move In Special!</h1>
                <li>Move in by June 3rd, 2019, First Month's Rent 50% Off!</li>
                <li>Rent a garage and receive $25 gift card to Target!</li>
                <li>Refer a friend to gain up $250 credit towards rent.</li>
        </div>
        <table>
          <tr>
            <td>
              <div class="card" style="width: 100%;" >
                <img id="card-image" class="card-img-top" style="width: 100%;"  src="{% static "images/825.jpg" %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">This 1220 square foot multi family home has 2 bedrooms and 3.0 bathrooms. It is located at 825 S 30th Ct Omaha, Nebraska.</p>
                  <a href="https://www.zillow.com/homedetails/825-S-30th-Ct-Omaha-NE-68105/244066172_zpid/?fullpage=true">View Listing on Zillow</a>
                </div>
              </div>
            </td>
            <td>
              <div class="card" style="width: 100%;" >
                <img id="card-image"class="card-img-top" style="width: 100%;" src="{% static "images/827.jpg" %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">This 1220 square foot multi family home has 2 bedrooms and 3.0 bathrooms. It is located at 827 S 30th Ct Omaha, Nebraska.</p>
                  <a href="https://www.zillow.com/homedetails/827-S-30th-Ct-Omaha-NE-68105/244066155_zpid/?fullpage=true">View Listing on Zillow</a>
                </div>
              </div>
            </td>
            <td>
              <div class="card" style="width: 100%;" >
                <img id="card-image" class="card-img-top" style="width: 100%;"  src="{% static "images/921.jpg" %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">This 1470 square foot multi family home has 2 bedrooms and 3.0 bathrooms. It is located at 921 S 31st St Omaha, Nebraska.</p>
                  <a href="https://www.zillow.com/homedetails/921-S-31st-St-Omaha-NE-68105/244067680_zpid/?fullpage=true">View Listing on Zillow</a>
                </div>
              </div>
            </td>
          </tr>
        </table>
      </div>

  {% endblock %}

pichik_development/webapp/templates/webapp/secondlisting.html
<!DOCTYPE html>
{% extends "webapp/base.html" %}
{% load staticfiles %}

  {% block body_block %}
    <div class="container">
      <div id="jumbo1" class="jumbotron">
        <div class="media">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img id="car-img" src="{% static "images/827-A.jpg" %}"  alt="...">
              </div>
              <div class="carousel-item">
                <img id="car-img" src="{% static "images/827-B.jpg" %}" alt="...">
              </div>
              <div class="carousel-item">
                <img id="car-img" src="{% static "images/827-C.jpg" %}"  alt="...">
              </div>
              <div class="carousel-item">
                <img id="car-img" src="{% static "images/827.jpg" %}"  alt="...">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <div class="media-body">
            <h5 class="mt-0">827 S 30th Ct Omaha, Nebraska</h5>
            <div class="container">
                Bedrooms: 2 <br>
                Bathrooms: 2.5 <br>
                Heating: Forced air <br>
                Floor size: 1,220 sqft <br>
                Rooms: 6 <br>
                Appliances: Dishwasher, Garbage Disposal, Microwave <br>
            </div>
          </div>
        </div>
      </div>
    </div>

  {% endblock %}

pichik_development/webapp/templates/webapp/thirdlisting.html
<!DOCTYPE html>
{% extends "webapp/base.html" %}
{% load staticfiles %}

  {% block body_block %}
    <div class="container">
      <div id="jumbo1" class="jumbotron">
        <div class="media">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img id="car-img" src="{% static "images/825-AB.jpg" %}"  alt="...">
              </div>
              <div class="carousel-item">
                <img id="car-img" src="{% static "images/825-A.jpg" %}" alt="...">
              </div>
              <div class="carousel-item">
                <img id="car-img" src="{% static "images/825-B.jpg" %}"  alt="...">
              </div>
              <div class="carousel-item">
                <img id="car-img" src="{% static "images/825-C.jpg" %}"  alt="...">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <div class="media-body">
            <h5 class="mt-0">825 S 30th Ct Omaha, Nebraska.</h5>
            <div class="container">
                Bedrooms: 2 <br>
                Bathrooms: 2.5 <br>
                Heating: Forced air <br>
                Floor size: 1,220 sqft <br>
                Rooms: 6 <br>
                Appliances: Dishwasher, Garbage Disposal, Microwave <br>
            </div>
          </div>
        </div>
      </div>
    </div>

  {% endblock %}